Extend `acorn-walk` `baseVisitor` with all Nodes from `TSESTree`
So that the simple() walk function doesn't throw when it encounters a Node type it doesn't know about. Previously it failed with:

TypeError: baseVisitor[type] is not a function
 ❯ c node_modules/acorn-walk/dist/walk.mjs:23:22
 ❯ Object.skipThrough node_modules/acorn-walk/dist/walk.mjs:180:37
 ❯ c node_modules/acorn-walk/dist/walk.mjs:23:22
 ❯ Object.base.Program.base.BlockStatement.base.StaticBlock node_modules/acorn-walk/dist/walk.mjs:192:5
 ❯ c node_modules/acorn-walk/dist/walk.mjs:23:22
 ❯ Module.simple node_modules/acorn-walk/dist/walk.mjs:25:5
 ❯ SourceFile.analyzeClassDeclarations src/source_file.ts:305:5
    303|
    304|   analyzeClassDeclarations() {
    305|     simple(this.ast, {
       |     ^
    306|       ClassDeclaration: node => {
    307|         const className = ast.extractIdentifier(node.id)
 ❯ SourceFile.analyze src/source_file.ts:184:12
 ❯ src/project.ts:169:65